package com.msa.account.entity;

public enum Role {
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MOBILE_DEVELOPER,
    DATA_ENGINEER,
    AI_ENGINEER,
    DESIGNER,PLANNER
}
